### ISSUE TITLE
与原生代码交互失败

### ISSUE THREAD

**Issue by JerryMissTom** [azhon/ReactNative#1]
我参考你与原生交互的代码，唤起android的Toast是可以的，但是唤起号码盘，回调都失败，点击按钮无反应。

**Comment by JerryMissTom** [comment]
修改Native代码后是否需要重新Gradle并且重启模拟器？

**Comment by azhon** [comment]
你仔细跟我的代码对比一下，看是不是少了什么代码！
模拟器是不需要重启的，应用重新更新就可以了。

**Comment by JerryMissTom** [comment]
我检查了几遍，并未发现什么不同，唤起号码盘需要的permission我也设置了，但是在App.js中，`Android.callPhone(Android.TEL);`这个Android.TE变量并未在Java代码中定义，为何会直接使用呢

**Comment by JerryMissTom** [comment]
我今天重新构建项目后发现可以调用了，我猜测是我添加Native代码后并未重新Gradle项目，导致调用原生的功能失败。

**Comment by Songhongxin1** [comment]
我R，不能用stack来作为容器来套tab，不然疯狂点击back界面会空白，作者完全是在误人子弟，LJ！！
